name: Genera Articoli

on:
  schedule:
    - cron: '0 20 * * *'  # Ogni giorno alle 18:00 CET
  workflow_dispatch:

jobs:
  generate_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install duckduckgo-search beautifulsoup4 requests markdownify nltk transformers torch

      - name: Run script
        run: python generate_posts.py

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _posts/*.md
          git commit -m "Nuovi articoli generati automaticamente"
          git push
